# Generated by Django 4.0.3 on 2022-03-27 19:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=250)),
                ('speech_date', models.DateField()),
                ('speech_text', models.TextField()),
                ('search_speech_text', django.contrib.postgres.search.SearchVectorField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Speeches',
                'ordering': ['speech_date'],
            },
        ),
        migrations.AddIndex(
            model_name='speech',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_speech_text'], name='sotu_speech_search__e67881_gin'),
        ),
    ]
